apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-edit
spec:
  selector:
    matchLabels:
      app: create-edit
  replicas: 1
  template:
    metadata:
      labels:
        app: create-edit
    spec:
      containers:
        - name: create-edit
          image: gcr.io/${{ secrets.GKE_PROJECT_ID }}/create-edit:${{ github.sha }}
          ports:
            - containerPort: 8081
